library(stringr)
library(dplyr)
library(lubridate)
library(car)
library(survival)
library(ReporteRs)
# if(!require(devtools)) install.packages("devtools")
# devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
library(survminer)#fonction ggsurv
library(knitr)
library(gridExtra)
library(grid)
library(GGally)
library(scales)

